name 'renanvicente-urleater'
version '0.0.1'
author 'Renan Vicente'
license 'Apache2'
project_page 'http://www.renanvicente.com'
source 'https://github.com/renanvicente/puppet-urleater-get'
summary 'Puppet module for urleater'
description 'This module installs and manages urleater. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'puppetlabs-vcsrepo'
